### ISSUE TITLE
Self closing and non-closing tags

### ISSUE THREAD

**Issue by orlov-vo** [UnwrittenFun/prettier-plugin-svelte#10] opened 2019-05-06 14:13 UTC
What you think about handle non-closing tags?

```html
<div />
```

It's short, but it is not a valid html. It should be like this:
```html
<div></div>
```

I can create PR from my fork of this repository if needed: https://github.com/orlov-vo/prettier-plugin-svelte/commit/53392b81804205f1abf7a9945be900f4e4c5bd54

**Comment by UnwrittenFun** [comment] 2019-05-07 18:07
I am generally in favour of `<div />`. I don't think we need to worry about if its strictly valid html5 as the svelte compiler handles it therefore it is valid svelte

**Comment by UnwrittenFun** [comment] 2019-05-12 11:18
Closing this as its working as intended right now, feel free to continue the discussion

**Closed by UnwrittenFun** 2019-05-12 11:18 UTC

**Comment by aredridel** [comment] 2020-04-03 20:39
Aye. I wish this had broken the other way — it means svelte can't be syntax-highlighted with plain HTML tools.
